language:
  php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pecl install uopz
  - composer install --dev --no-interaction --prefer-source

script:
  - make phpcs
  - make phpmd
  - make phpunit ARGS=--testsuite=unit
